---
title: "Additional analysis"
author: "Andrew Heiss and Suparna Chaudhry"
date: "Last run: `r format(Sys.time(), '%B %e, %Y')`"
output: 
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r load-libraries-data, warning=FALSE, message=FALSE}
# Unload all the already-loaded packages because R Markdown websites *don't* knit 
# each Rmd in a separate environment: https://github.com/rstudio/rmarkdown/issues/1326
#
# This means that here::here() and lubridate::here() will conflict becuase **here**
# has already been loaded in previous scripts
if (isTRUE(getOption('knitr.in.progress')) & !is.null(names(sessionInfo()$otherPkgs))) {
  invisible(suppressWarnings(sapply(paste0("package:", names(sessionInfo()$otherPkgs)),
                                    detach, character.only = TRUE)))
}

# Load libraries again
library(tidyverse)
library(rstanarm)
library(broom)
library(coda)
library(glue)
library(ggstance)
library(ggridges)
library(grid)
library(Gmisc)
library(patchwork)
library(pander)
library(scales)
library(huxtable)
library(lubridate)
library(modelr)
library(here)

source(file.path(here(), "lib", "graphics.R"))
source(file.path(here(), "lib", "pander_options.R"))
source(file.path(here(), "lib", "modeling.R"))

# Load data
results <- readRDS(file.path(here(), "data", "results_clean.rds"))
```

# CONSORT flow

```{r build-consort, results="hide", fig.width=10, fig.height=6}
consort <- readRDS(file.path(here(), "data", "completion_summary.rds")) %>% 
  spread(reason, n) %>% 
  mutate(group = 1:n(),
         assigned = Approved + `Failed first attention check`,
         issue = str_replace_all(issue, "assistance", "assist.")) %>% 
  mutate(assigned_label = glue("Allocated to Group {group}\n{crackdown}\n{issue}\n{funding} funding\n\nN = {assigned}"),
         completed_label = glue("Completed\nN = {Approved}\n\n{`Failed first attention check`} failed\nattention check"))

assessed_eligibility_n <- sum(consort$Approved, consort$`Failed first attention check`, 
                              consort$`Took survey outisde of MTurk`)
ineligible_n <- sum(consort$`Took survey outisde of MTurk`)
randomized_n <- sum(consort$Approved, consort$`Failed first attention check`)


# https://aghaynes.wordpress.com/2018/05/09/flow-charts-in-r/
# set some parameters to use repeatedly
width <- 0.1
xs <- seq(0.1, 0.9, length.out = 8)
allocated_y <- 0.375
completed_y <- 0.125

box_gp_grey <- gpar(fill = ngo_cols("light grey"))
box_gp_blue_dk <- gpar(fill = ngo_cols("blue"), alpha = 0.75)
box_gp_blue_lt <- gpar(fill = ngo_cols("blue"), alpha = 0.35)
box_gp_green <- gpar(fill = ngo_cols("green"), alpha = 0.65)
box_gp_yellow <- gpar(fill = ngo_cols("yellow"))
box_gp_orange <- gpar(fill = ngo_cols("orange"), alpha = 0.65)

txt_gp <- gpar(fontfamily = "Encode Sans Condensed Medium", 
               fontface = "plain", fontsize = 8)

# Create boxes
total <- boxGrob(glue("Assessed for eligibility\n N = {assessed_eligibility_n}"), 
                 x = 0.5, y = 0.9, width = 2 * width,
                 box_gp = box_gp_blue_lt, txt_gp = txt_gp)
randomized <- boxGrob(glue("Randomized\n N = {randomized_n}"), 
                      x = 0.5, y = 0.65, width = 2 * width,
                      box_gp = box_gp_blue_dk, txt_gp = txt_gp)
ineligible <- boxGrob(glue("Participants excluded for\ncompleting Qualtrics survey\noutside of MTurk\n N = {ineligible_n}"), 
                      x = xs[7], y = 0.775, #width = 0.25,
                      box_gp = box_gp_yellow, txt_gp = txt_gp)

group1 <- boxGrob(filter(consort, group == 1)$assigned_label,
                  x = xs[1], y = allocated_y, width = width, 
                  box_gp = box_gp_orange, txt_gp = txt_gp)
group2 <- boxGrob(filter(consort, group == 2)$assigned_label,
                  x = xs[2], y = allocated_y, width = width, 
                  box_gp = box_gp_orange, txt_gp = txt_gp)
group3 <- boxGrob(filter(consort, group == 3)$assigned_label,
                  x = xs[3], y = allocated_y, width = width, 
                  box_gp = box_gp_orange, txt_gp = txt_gp)
group4 <- boxGrob(filter(consort, group == 4)$assigned_label,
                  x = xs[4], y = allocated_y, width = width, 
                  box_gp = box_gp_orange, txt_gp = txt_gp)
group5 <- boxGrob(filter(consort, group == 5)$assigned_label,
                  x = xs[5], y = allocated_y, width = width, 
                  box_gp = box_gp_orange, txt_gp = txt_gp)
group6 <- boxGrob(filter(consort, group == 6)$assigned_label,
                  x = xs[6], y = allocated_y, width = width, 
                  box_gp = box_gp_orange, txt_gp = txt_gp)
group7 <- boxGrob(filter(consort, group == 7)$assigned_label,
                  x = xs[7], y = allocated_y, width = width, 
                  box_gp = box_gp_orange, txt_gp = txt_gp)
group8 <- boxGrob(filter(consort, group == 8)$assigned_label,
                  x = xs[8], y = allocated_y, width = width, 
                  box_gp = box_gp_orange, txt_gp = txt_gp)

group1_completed <- boxGrob(filter(consort, group == 1)$completed_label, 
                            x = xs[1], y = completed_y, width = width,
                            box_gp = box_gp_green, txt_gp = txt_gp)
group2_completed <- boxGrob(filter(consort, group == 2)$completed_label, 
                            x = xs[2], y = completed_y, width = width,
                            box_gp = box_gp_green, txt_gp = txt_gp)
group3_completed <- boxGrob(filter(consort, group == 3)$completed_label, 
                            x = xs[3], y = completed_y, width = width,
                            box_gp = box_gp_green, txt_gp = txt_gp)
group4_completed <- boxGrob(filter(consort, group == 4)$completed_label, 
                            x = xs[4], y = completed_y, width = width,
                            box_gp = box_gp_green, txt_gp = txt_gp)
group5_completed <- boxGrob(filter(consort, group == 5)$completed_label, 
                            x = xs[5], y = completed_y, width = width,
                            box_gp = box_gp_green, txt_gp = txt_gp)
group6_completed <- boxGrob(filter(consort, group == 6)$completed_label, 
                            x = xs[6], y = completed_y, width = width,
                            box_gp = box_gp_green, txt_gp = txt_gp)
group7_completed <- boxGrob(filter(consort, group == 7)$completed_label, 
                            x = xs[7], y = completed_y, width = width,
                            box_gp = box_gp_green, txt_gp = txt_gp)
group8_completed <- boxGrob(filter(consort, group == 8)$completed_label, 
                            x = xs[8], y = completed_y, width = width,
                            box_gp = box_gp_green, txt_gp = txt_gp)

# Connect boxes
grid.newpage()
total; randomized; ineligible
connectGrob(total, randomized, "v")
connectGrob(total, ineligible, "-")

group1; group2; group3; group4; group5; group6; group7; group8
connectGrob(randomized, group1, "N")
connectGrob(randomized, group2, "N")
connectGrob(randomized, group3, "N")
connectGrob(randomized, group4, "N")
connectGrob(randomized, group5, "N")
connectGrob(randomized, group6, "N")
connectGrob(randomized, group7, "N")
connectGrob(randomized, group8, "N")

group1_completed; group2_completed; group3_completed; group4_completed; 
group5_completed; group6_completed; group7_completed; group8_completed
connectGrob(group1, group1_completed, "N")
connectGrob(group2, group2_completed, "N")
connectGrob(group3, group3_completed, "N")
connectGrob(group4, group4_completed, "N")
connectGrob(group5, group5_completed, "N")
connectGrob(group6, group6_completed, "N")
connectGrob(group7, group7_completed, "N")
connectGrob(group8, group8_completed, "N")

# Use a global plot device temporarily because each chunk starts a new viewport
# and I want to use grid.grab() on this chunk, but I also want to hide the
# output from grid.grab() since knitr/grid inexplicably insist on plotting a
# second figure even when wrapping grid.grab() in invisible() or enabling
# results="hide" in the chunk options. So, the hacky solution here is to use a
# global device, capture the grid output in a new chunk that isn't included, and
# turn off the global plot device later. I also include code that isn't run for
# the sake of readability (i.e. fig_consort would come out of nowhere otherwise)
#
# See https://stackoverflow.com/a/17509770/120898
knitr::opts_knit$set(global.device = TRUE)
```

```{r grab-figure-actual, include=FALSE}
fig_consort <- grid.grab()
```

```{r grab-figure-fake, eval=FALSE}
fig_consort <- grid.grab()
```

```{r show-save-consort, fig.width=10, fig.height=6}
# Turn off global device
knitr::opts_knit$set(global.device = FALSE)

fig_consort %T>%
  ggsave(., filename = file.path(here(), "output", "figures", "consort.pdf"),
         width = 10, height = 6, units = "in", device = cairo_pdf) %>% 
  ggsave(., filename = file.path(here(), "output", "figures", "consort.png"),
         width = 10, height = 6, units = "in", type = "cairo", dpi = 300)
```


# Miscellaneous survey details

## Average time to complete survey

```{r avg-time, results="asis"}
results %>% 
  summarize_at(vars(duration), funs(min, max, mean, sd, median)) %>% 
  gather(Statistic, value) %>% 
  mutate(value = seconds_to_period(value)) %>% 
  mutate(Minutes = sprintf("%02.0f:%02.0f", minute(value), second(value))) %>% 
  select(-value) %>% 
  pandoc.table()
```

## Attention check #2

```{r attention-check-2, results="asis"}
results %>% count(attention2_correct) %>% 
  rename(`Attention check 2 correct` = attention2_correct, Count = n) %>% 
  pandoc.table()
```

\

# Amount donated (full)

## Models

```{r build-models-amount-full, warning=FALSE, message=FALSE, cache=TRUE}
# Basic model
m_amount_c <- stan_glm(amount_donate ~ crackdown,
                       data = results, family = gaussian(),
                       prior = cauchy(location = 0, scale = 2.5),
                       prior_intercept = cauchy(location = 0, scale = 10),
                       chains = CHAINS, iter = ITER, warmup = WARMUP, seed = BAYES_SEED)

m_amount_ci <- update(m_amount_c, . ~ . + issue + crackdown * issue)

m_amount_cif <- update(m_amount_c, . ~ . + 
                         issue + funding + crackdown * issue + crackdown * funding + 
                         issue * funding + crackdown * issue * funding)

# Interaction models with extra controls
m_amount_c_full <- update(m_amount_c, . ~ . + 
                            favor_humanitarian_bin + 
                            give_charity_3 + volunteer + political_knowledge_bin +
                            ideology_bin + education_bin + religiosity_bin +
                            income_bin + age_bin)

m_amount_ci_full <- update(m_amount_ci, . ~ . + 
                             favor_humanitarian_bin + 
                             give_charity_3 + volunteer + political_knowledge_bin +
                             ideology_bin + education_bin + religiosity_bin +
                             income_bin + age_bin)

m_amount_cif_full <-update(m_amount_cif, . ~ . + 
                             favor_humanitarian_bin +
                             give_charity_3 + volunteer + political_knowledge_bin +
                             ideology_bin + education_bin + religiosity_bin +
                             income_bin + age_bin)
```

```{r tbl-models-amount-full, warning=FALSE, results="asis"}
huxreg(m_amount_c, m_amount_ci, m_amount_cif, 
       m_amount_c_full, m_amount_ci_full, m_amount_cif_full,
       coefs = clean_coefs_named,
       statistics = model_stats_bayes,
       stars = NULL) %T>% 
  print_hux() %>% 
  to_md(max_width = 100) %>% 
  cat(file = file.path(here(), "output", "tables", "tbl-models-amount-full.md"))
```

## Coefficient plot

```{r models-coefs-plot-amount, warning=FALSE, message=FALSE, fig.width=8, fig.height=5}
posterior_details <- data_frame(model_name = c("Basic model", "Full model"),
                                model = list(m_amount_cif,
                                             m_amount_cif_full)) %>% 
  mutate(posterior = model %>% map(~ as_data_frame(.)),
         tidy_summary = model %>% map(~ tidyMCMC(., conf.int = TRUE, conf.level = 0.9,
                                                 conf.method = "HPDinterval"))) 

coefs_posterior <- posterior_details %>%
  unnest(posterior) %>% 
  gather(term, value, -model_name) %>% 
  left_join(clean_coefs, by = "term") %>% 
  filter(term_clean != "Intercept") %>% 
  mutate(full_model = !simple_model)

coefs_summary <- posterior_details %>% 
  unnest(tidy_summary) %>% 
  left_join(clean_coefs, by = "term") %>% 
  filter(term_clean != "Intercept") %>% 
  mutate(full_model = !simple_model)

ggplot(coefs_posterior, aes(x = value, y = fct_rev(term_clean_fct))) +
  stat_density_ridges(aes(fill = model_name), alpha = 0.6, color = "black",
                      rel_min_height = 0.01, scale = 1.5, 
                      quantile_lines = TRUE, quantiles = 2) +
  geom_segment(data = coefs_summary, 
               aes(x = conf.low, xend = conf.high, 
                   y = fct_rev(term_clean_fct), yend = fct_rev(term_clean_fct)),
               size = 1) +
  geom_vline(xintercept = 0, linetype = "dotted", size = 1) + 
  scale_fill_manual(values = ngo_cols("red", "blue", name = FALSE), name = NULL) +
  labs(x = "Posterior median estimate + 90% credible interval", y = NULL,
       caption = "90% credible intervals shown in black. Solid vertical line = median; dotted vertical line = 0") +
  facet_wrap(~ full_model, scales = "free") + 
  theme_ngos() +
  theme(legend.position = "bottom",
        strip.text = element_blank())
```

## Predicted medians across different variables

**Charitable giving**

```{r plot-charity-amounts, fig.width=5, fig.height=4}
newdata_means <- results %>% 
  select(favor_humanitarian_bin, favor_human_rights_bin, favor_development_bin,
         give_charity_3, volunteer, political_knowledge_bin,
         ideology_bin, education_bin, religiosity_bin, income_bin, age_bin) %>% 
  summarize_all(typical) %>% 
  mutate(id = 1)

newdata_conditions_charity <- results %>% expand(nesting(crackdown, give_charity_3)) %>% 
  mutate(id = 1) %>% 
  left_join(select(newdata_means, -give_charity_3), by = "id") %>% 
  select(-id)

chains_fitted_charity <- posterior_linpred(m_amount_c_full, 
                                           newdata = newdata_conditions_charity)

coef_summary_charity <- newdata_conditions_charity %>% 
  bind_cols(tidyMCMC(as.mcmc(chains_fitted_charity), estimate.method = "median",
                     conf.int = TRUE, conf.level = 0.9, conf.method = "HPDinterval")) %>% 
  mutate_at(vars(crackdown, give_charity_3), funs(fct_inorder(., ordered = TRUE)))

ggplot(coef_summary_charity, aes(x = fct_rev(give_charity_3), y = estimate)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high, color = crackdown), 
                  position = position_dodge(width = 0.5)) +
  scale_color_manual(values = ngo_cols("orange", "green", name = FALSE), name = NULL) +
  scale_y_continuous(labels = dollar) +
  labs(x = "How often do you give to charity?", y = "Median amount donated") +
  theme_ngos() +
  theme(legend.position = "bottom",
        panel.grid.major.x = element_blank())
```

**Voluntarism and religiosity**

```{r plot-vol-relig-amounts}
newdata_conditions_vol_relig <- results %>% 
  expand(nesting(crackdown, volunteer, religiosity_bin)) %>% 
  filter(!is.na(religiosity_bin)) %>% 
  mutate(id = 1) %>% 
  left_join(select(newdata_means, -volunteer, -religiosity_bin), by = "id") %>% 
  select(-id)

chains_fitted_vol_relig <- posterior_linpred(m_amount_c_full, 
                                             newdata = newdata_conditions_vol_relig)

coef_summary_vol_relig <- newdata_conditions_vol_relig %>% 
  bind_cols(tidyMCMC(as.mcmc(chains_fitted_vol_relig), estimate.method = "median",
                     conf.int = TRUE, conf.level = 0.9, conf.method = "HPDinterval")) %>% 
  mutate_at(vars(crackdown, volunteer, religiosity_bin), funs(fct_inorder(., ordered = TRUE))) %>% 
  mutate(religiosity_bin = fct_recode(religiosity_bin,
                                      `Rarely attend religious services` = "Rarely",
                                      `Attend religious services\nat least once a month` = 
                                        "At least once a month"))

ggplot(coef_summary_vol_relig, aes(x = fct_rev(volunteer), y = estimate)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high, color = crackdown), 
                  position = position_dodge(width = 0.5)) +
  scale_color_manual(values = ngo_cols("orange", "green", name = FALSE), name = NULL) +
  scale_y_continuous(labels = dollar) +
  labs(x = "Have you volunteered in the last 12 months?", y = "Median amount donated") +
  facet_wrap(~ religiosity_bin) +
  theme_ngos() +
  theme(legend.position = "bottom",
        panel.grid.major.x = element_blank())
```


\

# Likelihood of donation (full)

## Models

```{r build-models-likely-full, warning=FALSE, message=FALSE, cache=TRUE}
# Basic models
m_likely_c <- stan_glm(donate_likely_bin ~ crackdown,
                       data = results, family = binomial(link = "logit"),
                       prior = student_t(3, 0, 2.5),
                       prior_intercept = student_t(3, 0, 10),
                       chains = CHAINS, iter = ITER, warmup = WARMUP, seed = BAYES_SEED)

m_likely_ci <- update(m_likely_c, . ~ . + issue + crackdown * issue)

m_likely_cif <- update(m_likely_c, . ~ . + 
                         issue + funding + crackdown * issue + crackdown * funding + 
                         issue * funding + crackdown * issue * funding)

# Interaction models with extra controls
m_likely_c_full <- update(m_likely_c, . ~ . + 
                            favor_humanitarian_bin +
                            give_charity_3 + volunteer + political_knowledge_bin +
                            ideology_bin + education_bin + religiosity_bin +
                            income_bin + age_bin)

m_likely_ci_full <- update(m_likely_ci, . ~ . + 
                             favor_humanitarian_bin +
                             give_charity_3 + volunteer + political_knowledge_bin +
                             ideology_bin + education_bin + religiosity_bin +
                             income_bin + age_bin)

m_likely_cif_full <-update(m_likely_cif, . ~ . + 
                             favor_humanitarian_bin +
                             give_charity_3 + volunteer + political_knowledge_bin +
                             ideology_bin + education_bin + religiosity_bin +
                             income_bin + age_bin)
```

```{r tbl-models-likely-full, warning=FALSE, results="asis"}
huxreg(m_likely_c, m_likely_ci, m_likely_cif, 
       m_likely_c_full, m_likely_ci_full, m_likely_cif_full,
       coefs = clean_coefs_named,
       statistics = model_stats_bayes,
       stars = NULL) %T>% 
  print_hux() %>% 
  to_md(max_width = 100) %>% 
  cat(file = file.path(here(), "output", "tables", "tbl-models-likelihood-full.md"))
```

## Coefficient plot

```{r models-coefs-plot-likely, warning=FALSE, message=FALSE, fig.width=8, fig.height=5}
posterior_details_likely <- data_frame(model_name = c("Basic model", "Full model"),
                                       model = list(m_likely_cif,
                                                    m_likely_cif_full)) %>% 
  mutate(posterior = model %>% map(~ as_data_frame(.)),
         tidy_summary = model %>% map(~ tidyMCMC(., conf.int = TRUE, conf.level = 0.9,
                                                 conf.method = "HPDinterval"))) 

coefs_posterior_likely <- posterior_details_likely %>%
  unnest(posterior) %>% 
  gather(term, value, -model_name) %>% 
  left_join(clean_coefs, by = "term") %>% 
  filter(term_clean != "Intercept") %>% 
  mutate(full_model = !simple_model)

coefs_summary_likely <- posterior_details_likely %>% 
  unnest(tidy_summary) %>% 
  left_join(clean_coefs, by = "term") %>% 
  filter(term_clean != "Intercept") %>% 
  mutate(full_model = !simple_model)

ggplot(coefs_posterior_likely, aes(x = value, y = fct_rev(term_clean_fct))) +
  stat_density_ridges(aes(fill = model_name), alpha = 0.6, color = "black",
                      rel_min_height = 0.01, scale = 1.5, 
                      quantile_lines = TRUE, quantiles = 2) +
  geom_segment(data = coefs_summary_likely, 
               aes(x = conf.low, xend = conf.high, 
                   y = fct_rev(term_clean_fct), yend = fct_rev(term_clean_fct)),
               size = 1) +
  geom_vline(xintercept = 0, linetype = "dotted", size = 1) + 
  scale_fill_manual(values = ngo_cols("red", "blue", name = FALSE), name = NULL) +
  labs(x = "Posterior median estimate + 90% credible interval", y = NULL,
       caption = "90% credible intervals shown in black. Solid vertical line = median; dotted vertical line = 0") +
  facet_wrap(~ full_model, scales = "free") + 
  theme_ngos() +
  theme(legend.position = "bottom",
        strip.text = element_blank())
```
