---
title: "Experimental design"
date: "Last run: `r format(Sys.time(), '%F')`"
bibliography: Manuscript/bibliography.bib
---

## Goal

The ultimate goal of our research project is to use Bayesian analysis is to test if the region of practical equivalence around the null value (i.e. the proposition that the average treatment effect of NGO crackdown is zero) excludes the posterior 95% HDI.

In this initial pilot study, we use standard frequentist methods to [perform power analysis](power.html) and estimate the desired sample size. We will use the effect size estimates from this study to inform the prior distribution of parameter values in future Bayesian-based experiments [@Kruschke:2015, 362]. 

## Experimental conditions

| Condition            | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|----------------------|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| **Crackdown**        |   |   |   |   |   |   |   |   |
| Yes                  | • | • | • | • |   |   |   |   |
| No                   |   |   |   |   | • | • | • | • |
| *Expected donations* | + | + | + | + | ∅ | ∅ | ∅ | ∅ |
|                      |   |   |   |   |   |   |   |   |
| **Issue area**       |   |   |   |   |   |   |   |   |
| Humanitarian service | • | • |   |   | • | • |   |   |
| Human rights         |   |   | • | • |   |   | • | • |
| *Expected donations* | + | + | − | − | + | + | − | − |
|                      |   |   |   |   |   |   |   |   |
| **Type of funding**  |   |   |   |   |   |   |   |   |
| Government           | • |   | • |   | • |   | • |   |
| Private              |   | • |   | • |   | • |   | • |
| *Expected donations* | − | + | − | + | − | + | − | + |

## References
