---
title: "NGO Crackdowns and Philanthropy"
author: "Suparna Chaudhry and Andrew Heiss"
date: "Last run: `r format(Sys.time(), '%F')`"
---

## Abstract

State crackdown on non-governmental organizations (NGOs), particularly through legal restrictions on funding, has become increasingly common. How do legal restrictions on NGOs impact patterns of private philanthropic giving and individual donor decision-making? With reduced funding for NGOs working on contentious issues, and an absence of philanthropic culture in many developing countries, many NGOs rely on funds from private donors in Western countries. Using a survey experiment, we explore how this crackdown changes donors' preferences based on the issue area and funding sources of the NGO. We find that private donors are responsive to the legal difficulties international NGOs face abroad and are more likely to donate to legally besieged privately funded human rights NGOs. Additionally, already-likely donors give substantially more to legally restricted NGOs working on humanitarian issues. We conclude by discussing the implications for the sustainability of NGOs working abroad.
