---
title: "Power analysis"
date: "Last run: `r format(Sys.time(), '%F')`"
---

## $f^2$ power analysis

```{r power-calculations}
library(pwr)
u_mine <- 1
# f2_mine <- cohen.ES(test = "f2", size = "small")$effect.size
f2_mine <- 0.02
sig_level_mine <- 0.05
power_mine = 0.90

survey_power <- pwr.f2.test(u=u_mine, v=NULL, f2=f2_mine, 
                            sig.level=sig_level_mine, power=power_mine)

# n = u + v + 1
n_total <- survey_power$u + survey_power$v + 1
n_group <- n_total / (2 * 2 * 2)
```

Cohen's rules of thumb for $f^2$ power are 0.02, 0.15, and 0.35 for small, medium, and large effect sizes.

We are using a [2 × 2 × 2 design](design.html), manipulating the experimental condition, the issue area for the NGO, and the source of funding for the NGO. The formula for calculating the $f^2$-based sample size with [`pwr.f2.test`](https://www.rdocumentation.org/packages/pwr/versions/1.2-0/topics/pwr.f2.test) requires the following values:

- `u`: degrees of freedom for the numerator. This is a 2 × 2 × 2 design, so the degrees of freedom = $(2 - 1) \times (2 - 1) \times (2 - 1) = 1$
- `f2`: effect size. Here we use a small size, or `r f2_mine`.
- `sig.level`: significance level, or Type I error probability. Here we use `r sig_level_mine`.
- `power`: power of test, or 1 − Type II error probability. Here we use `r power_mine`.

Given these parameters, `pwr.f2.test` yields `v`, or the degrees of freedom for the denominator. The final sample size `n` is calculated as `u + v + 1`.

Thus, the total sample size is **`r round(n_total, 2)`**, with **`r round(n_group, 2)`** spread across 8 groups.
