---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below. 
Title <- "The effect of NGO crackdowns on individual philanthropy"
```

# The effect of NGO crackdowns on individual philanthropy

[Suparna Chaudhry](http://www.suparnachaudhry.com/) • Department of Political Science • Christopher Newport University  
[Andrew Heiss](https://www.andrewheiss.com/) • Romney Institute of Public Service and Ethics • Brigham Young University

---


### Abstract

State crackdown on non-governmental organizations (NGOs), particularly through legal restrictions on funding, has become increasingly common. How do legal restrictions on NGOs impact patterns of private philanthropic giving and individual donor decision-making? With reduced funding for NGOs working on contentious issues, and an absence of philanthropic culture in many developing countries, many NGOs rely on funds from private donors in Western countries. Using a survey experiment, we explore how this crackdown changes donors' preferences based on the issue area and funding sources of the NGO. We find that private donors are responsive to the legal difficulties international NGOs face abroad and are more likely to donate to legally besieged privately funded human rights NGOs. Additionally, already-likely donors give substantially more to legally restricted NGOs working on humanitarian issues. We conclude by discussing the implications for the sustainability of NGOs working abroad.

---

This repository contains the data and code for our paper:

> Authors, (YYYY). _`r Title`_. Name of journal/book <https://doi.org/xxx/xxx>

Our pre-print is online here:

> Authors, (YYYY). _`r Title`_. Name of journal/book, Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/xxx/xxx>


### How to cite

Please cite this compendium as:

> Authors, (`r format(Sys.Date(), "%Y")`). _Compendium of R code and data for `r Title`_. Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/xxx/xxx>


### How to download or install

You can download the compendium as a zip from from this URL: </archive/master.zip>

Or you can install this compendium as an R package, testingthing, from GitHub with:

```r
pkgbuild::compile_dll()
```

### Licenses

**Text and figures :**  [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)

**Code :** See the [DESCRIPTION](DESCRIPTION) file

**Data :** [CC-0](http://creativecommons.org/publicdomain/zero/1.0/) attribution requested in reuse


### Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.md). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.

